
version: "3.2"

services:
  storage:
    restart: "always"
    container_name: giveaway-premium-client
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "0.0.0.0"
    environment:
      - PORT=1337
      - SERVER_URL=https://giveaway-premium.herokuapp.com/api
      - NODE_PATH=src
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_STATE=PRODUCTION
      - REACT_NEED_DEBUG=true
      - GENERATE_SOURCEMAP=false
      - NODE_OPTIONS=--max_old_space_size=1024
      - PORT = 3003
      - API_APP=https://giveaway-premium.herokuapp.com/api
      - APP_ID=EJKfA5jFxiC98aMbvir0vSAuDHO4NQ7x
      - APP_NAME=GIVEAWAY_PREMIUM
      - JAVASCRIPT_KEY=npx9ZOI6fokHfvaJQjDjidPnogS8PCH0
      - REST_API_KEY=6t7KSmWTkxxuvrF3a1jfqT6Vu0suWfEY
      - SERVER_URL=https://giveaway-premium.herokuapp.com/api
    ports:
      - "127.0.0.1:1337:1337"
      
